#############################################################################
# Makefile for building: fitsviewer
# Generated by qmake (2.01a) (Qt 4.8.4) on: gio mar 6 12:34:25 2014
# Project:  fitsviewer.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile fitsviewer.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -std=c++11 -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I-I/usr/include/CCfits -I. -I/usr/include/CCfits
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -L/usr/include/CCfits -lCCfits -lcfitsio -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = fitsviewer.cxx \
		main.cxx \
		QFitsWindow.cxx \
		FitsPhoto.cxx \
		FitsToImage.cxx \
		QFitsStretchDock.cxx \
		QFitsListWidgetItem.cxx moc_fitsviewer.cpp \
		moc_QFitsStretchDock.cpp \
		moc_QFitsWindow.cpp
OBJECTS       = fitsviewer.o \
		main.o \
		QFitsWindow.o \
		FitsPhoto.o \
		FitsToImage.o \
		QFitsStretchDock.o \
		QFitsListWidgetItem.o \
		moc_fitsviewer.o \
		moc_QFitsStretchDock.o \
		moc_QFitsWindow.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		fitsviewer.pro
QMAKE_TARGET  = fitsviewer
DESTDIR       = 
TARGET        = fitsviewer

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: fitsviewer.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile fitsviewer.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile fitsviewer.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/fitsviewer1.0.0 || $(MKDIR) .tmp/fitsviewer1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/fitsviewer1.0.0/ && $(COPY_FILE) --parents fitsviewer.h QFitsStretchDock.h QFitsWindow.h .tmp/fitsviewer1.0.0/ && $(COPY_FILE) --parents fitsviewer.cxx main.cxx QFitsWindow.cxx FitsPhoto.cxx FitsToImage.cxx QFitsStretchDock.cxx QFitsListWidgetItem.cxx .tmp/fitsviewer1.0.0/ && (cd `dirname .tmp/fitsviewer1.0.0` && $(TAR) fitsviewer1.0.0.tar fitsviewer1.0.0 && $(COMPRESS) fitsviewer1.0.0.tar) && $(MOVE) `dirname .tmp/fitsviewer1.0.0`/fitsviewer1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/fitsviewer1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_fitsviewer.cpp moc_QFitsStretchDock.cpp moc_QFitsWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_fitsviewer.cpp moc_QFitsStretchDock.cpp moc_QFitsWindow.cpp
moc_fitsviewer.cpp: QFitsWindow.h \
		FitsPhoto.h \
		settings.h \
		QFitsStretchDock.h \
		common.h \
		fitsviewer.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) fitsviewer.h -o moc_fitsviewer.cpp

moc_QFitsStretchDock.cpp: QFitsWindow.h \
		FitsPhoto.h \
		settings.h \
		QFitsStretchDock.h \
		common.h \
		QFitsStretchDock.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) QFitsStretchDock.h -o moc_QFitsStretchDock.cpp

moc_QFitsWindow.cpp: FitsPhoto.h \
		settings.h \
		QFitsStretchDock.h \
		QFitsWindow.h \
		common.h \
		QFitsWindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) QFitsWindow.h -o moc_QFitsWindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

fitsviewer.o: fitsviewer.cxx fitsviewer.h \
		QFitsWindow.h \
		FitsPhoto.h \
		settings.h \
		QFitsStretchDock.h \
		common.h \
		QFitsListWidgetItem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fitsviewer.o fitsviewer.cxx

main.o: main.cxx fitsviewer.h \
		QFitsWindow.h \
		FitsPhoto.h \
		settings.h \
		QFitsStretchDock.h \
		common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cxx

QFitsWindow.o: QFitsWindow.cxx QFitsWindow.h \
		FitsPhoto.h \
		settings.h \
		QFitsStretchDock.h \
		common.h \
		FitsToImage.h \
		fitsviewer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QFitsWindow.o QFitsWindow.cxx

FitsPhoto.o: FitsPhoto.cxx FitsPhoto.h \
		settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FitsPhoto.o FitsPhoto.cxx

FitsToImage.o: FitsToImage.cxx FitsToImage.h \
		FitsPhoto.h \
		settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FitsToImage.o FitsToImage.cxx

QFitsStretchDock.o: QFitsStretchDock.cxx QFitsStretchDock.h \
		QFitsWindow.h \
		FitsPhoto.h \
		settings.h \
		common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QFitsStretchDock.o QFitsStretchDock.cxx

QFitsListWidgetItem.o: QFitsListWidgetItem.cxx QFitsListWidgetItem.h \
		QFitsWindow.h \
		FitsPhoto.h \
		settings.h \
		QFitsStretchDock.h \
		common.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QFitsListWidgetItem.o QFitsListWidgetItem.cxx

moc_fitsviewer.o: moc_fitsviewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fitsviewer.o moc_fitsviewer.cpp

moc_QFitsStretchDock.o: moc_QFitsStretchDock.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_QFitsStretchDock.o moc_QFitsStretchDock.cpp

moc_QFitsWindow.o: moc_QFitsWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_QFitsWindow.o moc_QFitsWindow.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/lib/qt4/examples/widgets/imageviewer/ || $(MKDIR) $(INSTALL_ROOT)/usr/lib/qt4/examples/widgets/imageviewer/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/usr/lib/qt4/examples/widgets/imageviewer/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/usr/lib/qt4/examples/widgets/imageviewer/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/usr/lib/qt4/examples/widgets/imageviewer/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib/qt4/examples/widgets/imageviewer/ 


install_sources: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/lib/qt4/examples/widgets/imageviewer/ || $(MKDIR) $(INSTALL_ROOT)/usr/lib/qt4/examples/widgets/imageviewer/ 
	-$(INSTALL_FILE) /home/stefano/imageViewer/fitsviewer/fitsviewer.cxx $(INSTALL_ROOT)/usr/lib/qt4/examples/widgets/imageviewer/
	-$(INSTALL_FILE) /home/stefano/imageViewer/fitsviewer/main.cxx $(INSTALL_ROOT)/usr/lib/qt4/examples/widgets/imageviewer/
	-$(INSTALL_FILE) /home/stefano/imageViewer/fitsviewer/QFitsWindow.cxx $(INSTALL_ROOT)/usr/lib/qt4/examples/widgets/imageviewer/
	-$(INSTALL_FILE) /home/stefano/imageViewer/fitsviewer/FitsPhoto.cxx $(INSTALL_ROOT)/usr/lib/qt4/examples/widgets/imageviewer/
	-$(INSTALL_FILE) /home/stefano/imageViewer/fitsviewer/FitsToImage.cxx $(INSTALL_ROOT)/usr/lib/qt4/examples/widgets/imageviewer/
	-$(INSTALL_FILE) /home/stefano/imageViewer/fitsviewer/QFitsStretchDock.cxx $(INSTALL_ROOT)/usr/lib/qt4/examples/widgets/imageviewer/
	-$(INSTALL_FILE) /home/stefano/imageViewer/fitsviewer/QFitsListWidgetItem.cxx $(INSTALL_ROOT)/usr/lib/qt4/examples/widgets/imageviewer/
	-$(INSTALL_FILE) /home/stefano/imageViewer/fitsviewer/fitsviewer.h $(INSTALL_ROOT)/usr/lib/qt4/examples/widgets/imageviewer/
	-$(INSTALL_FILE) /home/stefano/imageViewer/fitsviewer/QFitsStretchDock.h $(INSTALL_ROOT)/usr/lib/qt4/examples/widgets/imageviewer/
	-$(INSTALL_FILE) /home/stefano/imageViewer/fitsviewer/QFitsWindow.h $(INSTALL_ROOT)/usr/lib/qt4/examples/widgets/imageviewer/


uninstall_sources:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/widgets/imageviewer/fitsviewer.cxx 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/widgets/imageviewer/main.cxx 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/widgets/imageviewer/QFitsWindow.cxx 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/widgets/imageviewer/FitsPhoto.cxx 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/widgets/imageviewer/FitsToImage.cxx 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/widgets/imageviewer/QFitsStretchDock.cxx 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/widgets/imageviewer/QFitsListWidgetItem.cxx 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/widgets/imageviewer/fitsviewer.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/widgets/imageviewer/QFitsStretchDock.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/lib/qt4/examples/widgets/imageviewer/QFitsWindow.h
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib/qt4/examples/widgets/imageviewer/ 


install:  install_target install_sources  FORCE

uninstall: uninstall_target uninstall_sources   FORCE

FORCE:

